### ISSUE TITLE
get_preview outputs "Read more"-link even if there aren't any more text to read

### ISSUE THREAD

**Issue by stianmartinsen** [timber/timber#1345]
When I'm using Timber's `get_preview`-function the "Read more"-link is always outputted – even if the post's text isn't longer than the preview.

I expected that there would at least be an option to stop this, but I couldn't find one. Am I missing something? Because why would a person want to click a link just to read the same text as he's already read?

**Comment by certainlyakey** [comment]
Yes, there's an option to stop this — set the third argument as `null`. Had the same problem but took a look at the source code.

**Comment by stianmartinsen** [comment]
[The third argument](https://github.com/timber/timber/blob/master/lib/Post.php#L390) is the text for the read more link. I do want read more links if the text is longer than the preview, so I don't think setting this to null is a good solution..?

**Comment by certainlyakey** [comment]
you're right. i had somewhat different problem, tried to remove it whatsoever.

**Comment by Djules** [comment]
The method `get_preview` is now deprecated, and using `{{ post.preview }}` doesn't allow any arguments, so this issue still exists.

If the user manually set an excerpt, it should not add the "Read more" link, no matter what, as the original WordPress function does…

**Comment by tameroski** [comment]
#1015 Should fix this but it doesn't seam to work ... Or i'm missing something.

**Comment by tameroski** [comment]
`{{post.preview}}` doesn't allow arguments but has modifiers like `{{post.preview.length(20).force.read_more("Keep Reading")}}`. See #1015 for details. Doesn't fix the issue though but may be usefull.

**Comment by acobster** [comment]
Tagged this with 2.0 in case it's still an issue that would require a breaking change to fix...

**Comment by gchtr** [comment]
Okay, I looked at it more closely and we need to do some changes to support this. We already have a `$trimmed` variable in the code that we can make use of. I already have some code ready locally. But I have several questions we should discuss first.

### 1. Should it be a global option or another argument for `Post::excerpt()`?

For a global option, we could use a filter. But since we already have a couple of parameter, using another parameter wouldn’t be that bad. Here’s how it could look like. (Be aware that this is how it would work in Timber 2.0).

```php
$excerpt = $post->excerpt( [
	'maybe_skip_read_more' => true,
] );
```

or in Twig

```twig
{{ post.excerpt({ maybe_skip_read_more: true }) }}
```

### 2. Should the option be enabled by default?

When we would enable it by default, it would be a breaking change.

> Because why would a person want to click a link just to read the same text as he's already read?

There can be different factors that need to be considered. Maybe you want to click it to copy the URL so you can share it with others. Maybe the read more link is the thing that provides the best affordance to click it. Maybe the read more links are deliberately designed in a way that suggests clicking on them instead of a title. If some teasers have a read more link and some don’t, you lose consistency in the design, which might be a stronger factor than correctness about the term "read more". Of course this all depends on the markup and the styles the excerpt is used with.

Instead of using "read more" as a text, you could also use "view" or "go". The meaning would change and the logic would be intact again.

Because we can’t know the real intention, I wouldn’t add this behavior as a default, but make it optional.

### 3. Should we have an option to make the `end` parameter optional?

I figured that for the `end` option in an excerpt, which is `…` (`&hellip;`), the same rules apply. If the excerpt text is not longer that the content itself, then you probably wouldn’t want to add a `&hellip;`.

```php
$excerpt = $post->excerpt( [
    'maybe_skip_end' => true,
] );
```

Contrary to point 2, I think this could be a default, because it’s closer attached to the text and not directly a part of a teaser functionality. Or maybe we could even consider this a bug. Because the `$trimmed` variable is always set to `true` and doesn’t compare the excerpt and content lengths yet.

https://github.com/timber/timber/blob/2.x/lib/PostPreview.php#L353

### 4. What should we call the option?

I’m still looking for a better word than "maybe_skip". The option should be a short name that says: "only add if excerpt is not trimmed".

- `maybe_skip_read_more` / `maybe_skip_end`
- `conditional_read_more` / `conditional_end`
- `no_read_more_when_untrimmed` / `no_end_when_untrimmed`

Maybe @jarednova and @acobster have some opinions about this, too.

**Comment by jarednova** [comment]
@gchtr I'm mostly in agreement, with a few points:

**1. Should it be a global option or another argument for Post::excerpt()?**
The syntax you have looks great. Perhaps there's a filter to set a global default as well, but this feels like something I'd be more likely to control when building the output/markup as you have it demonstrated.

**2. Should the option be enabled by default?**
I keep going back-and-forth on this one. The best argument I have to making this default is that there's nothing "more" to read and access to the post page is more likely to be used/controlled by a `{{ post.link }}` around the title. I'm 51/49 on what I think is best, which probably means either path is fine

**3. Should we have an option to make the end parameter optional?**
Yes, and agree with the implementation you suggest

**4. What should we call the option?**
I'm partial to the `maybe_` syntax b/c it's short and "conversational." The other one I'd suggest for consideration is `always_`, as in:
* `always_show_read_more: true` / `always_show_end: false`

**Comment by gchtr** [comment]
In the upcoming version 2 of Timber, this can be controlled with the `always_add_read_more` option when using post excerpts, see [`Timber\PostExcerpt::__construct()`](https://timber.github.io/docs/v2/reference/timber-postexcerpt/#__construct).
